[package]
name = "ivadsiuls/codekit"
description = "a roblox coding toolkit with everything you need to get started"
version = "1.0.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
vide = "centau/vide@0.4.0"
